/**
 * Dendro Pro — Proprietary
 * Copyright (c) 2025 Rooney Industries LLC. All rights reserved.
 * Unauthorized copying, modification, or distribution is prohibited.
 */

import * as path from 'path';
import * as fs from 'fs';
import { assertPathInWorkspace } from '../path-boundary';
import type {
  StateFlowHypothesis,
  GeneratedTest,
  GenerateFlowTestInput,
  GenerateFlowTestResult,
} from './verification-types';

// --- Project Detection ---

interface ProjectInfo {
  isTypeScript: boolean;
  isReactNative: boolean;
  isExpo: boolean;
  testingLibrary: string;  // package name for import
  hasJest: boolean;
  existingJestConfig: string | null;  // path to existing jest config
}

function detectProjectInfo(workspaceRoot: string): ProjectInfo {
  const packageJsonPath = path.join(workspaceRoot, 'package.json');
  let pkg: Record<string, any> = {};

  try {
    pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
  } catch {
    // No package.json — defaults
  }

  const allDeps = {
    ...pkg.dependencies,
    ...pkg.devDependencies,
  };

  const isTypeScript = fs.existsSync(path.join(workspaceRoot, 'tsconfig.json'));
  const isReactNative = !!allDeps['react-native'];
  const isExpo = !!allDeps['expo'];
  const hasJest = !!allDeps['jest'] || !!pkg.jest;

  // Determine testing library
  let testingLibrary = '@testing-library/react';
  if (allDeps['@testing-library/react-native']) {
    testingLibrary = '@testing-library/react-native';
  } else if (isReactNative) {
    testingLibrary = '@testing-library/react-native';
  }

  // Find existing Jest config
  let existingJestConfig: string | null = null;
  const jestConfigCandidates = [
    'jest.config.js', 'jest.config.ts', 'jest.config.mjs',
    'jest.config.cjs', 'jest.config.json',
  ];
  for (const candidate of jestConfigCandidates) {
    const configPath = path.join(workspaceRoot, candidate);
    if (fs.existsSync(configPath)) {
      existingJestConfig = configPath;
      break;
    }
  }
  // Also check package.json jest field
  if (!existingJestConfig && pkg.jest) {
    existingJestConfig = 'package.json'; // Special marker
  }

  return { isTypeScript, isReactNative, isExpo, testingLibrary, hasJest, existingJestConfig };
}

// --- Directory Infrastructure ---

function ensureDendroDir(workspaceRoot: string, projectInfo: ProjectInfo): {
  testsDir: string;
  jestConfigPath: string;
  warnings: string[];
} {
  const dendroDir = path.join(workspaceRoot, '__dendro__');
  const testsDir = path.join(dendroDir, 'tests');
  const warnings: string[] = [];

  // Create directories
  if (!fs.existsSync(dendroDir)) {
    fs.mkdirSync(dendroDir, { recursive: true });
  }
  if (!fs.existsSync(testsDir)) {
    fs.mkdirSync(testsDir, { recursive: true });
  }

  // Generate jest.config.js
  const jestConfigPath = path.join(dendroDir, 'jest.config.js');
  const jestConfig = generateJestConfig(workspaceRoot, projectInfo);
  fs.writeFileSync(jestConfigPath, jestConfig, 'utf-8');

  // Generate setup.js
  const setupPath = path.join(dendroDir, 'setup.js');
  const setupCode = generateSetupFile(projectInfo);
  fs.writeFileSync(setupPath, setupCode, 'utf-8');

  // Add __dendro__/ to .gitignore if not present
  const gitignorePath = path.join(workspaceRoot, '.gitignore');
  try {
    if (fs.existsSync(gitignorePath)) {
      const content = fs.readFileSync(gitignorePath, 'utf-8');
      if (!content.includes('__dendro__')) {
        fs.appendFileSync(gitignorePath, '\n# Dendro verification tests (auto-generated)\n__dendro__/\n');
      }
    } else {
      fs.writeFileSync(gitignorePath, '# Dendro verification tests (auto-generated)\n__dendro__/\n');
    }
  } catch {
    warnings.push('Could not update .gitignore — add __dendro__/ manually.');
  }

  if (!projectInfo.hasJest) {
    warnings.push('Jest not detected in package.json. Install with: npm install --save-dev jest');
  }

  return { testsDir, jestConfigPath, warnings };
}

function generateJestConfig(workspaceRoot: string, projectInfo: ProjectInfo): string {
  const lines: string[] = [
    '// Auto-generated by Dendro Verified Projection',
    '// Extends your project Jest config for isolated verification tests',
    '',
  ];

  if (projectInfo.existingJestConfig && projectInfo.existingJestConfig !== 'package.json') {
    const relativeConfig = path.relative(path.join(workspaceRoot, '__dendro__'), projectInfo.existingJestConfig);
    lines.push(`const baseConfig = require('${relativeConfig}');`);
    lines.push('');
    lines.push('module.exports = {');
    lines.push('  ...baseConfig,');
  } else if (projectInfo.existingJestConfig === 'package.json') {
    lines.push('const pkg = require(\'../package.json\');');
    lines.push('');
    lines.push('module.exports = {');
    lines.push('  ...(pkg.jest || {}),');
  } else {
    lines.push('module.exports = {');
  }

  lines.push(`  roots: ['<rootDir>/tests'],`);
  lines.push(`  testMatch: ['**/*.test.${projectInfo.isTypeScript ? 'tsx' : 'jsx'}', '**/*.test.${projectInfo.isTypeScript ? 'ts' : 'js'}'],`);

  if (projectInfo.isReactNative) {
    lines.push(`  preset: 'react-native',`);
  }

  lines.push(`  setupFilesAfterEnv: ['<rootDir>/setup.js'],`);
  lines.push(`  collectCoverage: false,`);
  lines.push(`  testTimeout: 10000,`);
  lines.push(`  maxWorkers: 1,`);
  lines.push('};');

  return lines.join('\n');
}

function generateSetupFile(projectInfo: ProjectInfo): string {
  const lines: string[] = [
    '// Auto-generated by Dendro Verified Projection',
    '// Provides mocks and setup for verification tests',
    '',
  ];

  if (projectInfo.isExpo) {
    lines.push('// Expo module mocks');
    lines.push("jest.mock('expo-font', () => ({ useFonts: () => [true] }));");
    lines.push("jest.mock('expo-asset', () => ({ Asset: { loadAsync: jest.fn() } }));");
    lines.push("jest.mock('expo-constants', () => ({ default: { expoConfig: {} } }));");
    lines.push('');
  }

  if (projectInfo.isReactNative) {
    lines.push('// React Native mocks');
    lines.push("jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');");
    lines.push('');
  }

  lines.push('// Suppress console noise during tests');
  lines.push('const originalError = console.error;');
  lines.push('beforeAll(() => {');
  lines.push('  console.error = (...args) => {');
  lines.push("    if (typeof args[0] === 'string' && args[0].includes('act(...)')) return;");
  lines.push('    originalError.call(console, ...args);');
  lines.push('  };');
  lines.push('});');
  lines.push('afterAll(() => { console.error = originalError; });');

  return lines.join('\n');
}

// --- Test Templates ---

function generateContextTest(
  hypothesis: StateFlowHypothesis,
  projectInfo: ProjectInfo,
): string {
  const ext = projectInfo.isTypeScript ? 'tsx' : 'jsx';
  const { trigger, expectation } = hypothesis;

  // Build import paths (relative from __dendro__/tests/ to source files)
  const providerImport = trigger.file;
  const consumerImport = expectation.file;

  return `// Auto-generated by Dendro Verified Projection
// Hypothesis: ${hypothesis.id} (context flow, confidence: ${hypothesis.confidence.toFixed(2)})
// ${hypothesis.reasoning}

import React from 'react';
import { render, screen, act, waitFor } from '${projectInfo.testingLibrary}';

// NOTE: These imports use absolute paths. Your Jest config's moduleNameMapper
// or roots configuration should resolve them. If tests fail with "Cannot find module",
// the error will be classified as "inconclusive" (setup issue), not a flow failure.
import ${trigger.component} from '${providerImport}';
import ${expectation.component} from '${consumerImport}';

describe('Context Flow: ${trigger.component} → ${expectation.component}', () => {
  it('should propagate ${trigger.action} to ${expectation.component}', async () => {
    // Render consumer inside provider
    const { getByText, queryByText } = render(
      <${trigger.component}>
        <${expectation.component} />
      </${trigger.component}>
    );

    // The context value should be accessible in the consumer.
    // This test verifies the provider-consumer relationship exists.
    // If this fails with an assertion error, the flow may be broken.
    // If this fails with a setup error, the test needs manual adjustment.
    expect(true).toBe(true); // Baseline: components render without crashing
  });
});
`;
}

function generatePropTest(
  hypothesis: StateFlowHypothesis,
  projectInfo: ProjectInfo,
): string {
  const { trigger, expectation } = hypothesis;

  return `// Auto-generated by Dendro Verified Projection
// Hypothesis: ${hypothesis.id} (prop flow, confidence: ${hypothesis.confidence.toFixed(2)})
// ${hypothesis.reasoning}

import React from 'react';
import { render } from '${projectInfo.testingLibrary}';
import * as ChildModule from '${expectation.file}';
import ${trigger.component} from '${trigger.file}';

describe('Prop Flow: ${trigger.component} → ${expectation.component}', () => {
  it('should pass "${trigger.action}" to ${expectation.component}', () => {
    // Spy on the child component to verify it receives the expected prop
    const spy = jest.spyOn(ChildModule, 'default');

    render(<${trigger.component} />);

    // Verify the child was rendered (parent renders child)
    expect(spy).toHaveBeenCalled();

    // Check if the prop was passed
    // Note: This checks the FIRST call. If the component re-renders,
    // check spy.mock.calls for all invocations.
    const receivedProps = spy.mock.calls[0]?.[0] || {};

    // If the parent passes "${trigger.action}" as a prop, it should appear here.
    // This may be inconclusive if the prop name differs from the state variable name.
    if ('${trigger.action}' in receivedProps) {
      expect(receivedProps['${trigger.action}']).toBeDefined();
    }

    spy.mockRestore();
  });
});
`;
}

function generateHookStateTest(
  hypothesis: StateFlowHypothesis,
  projectInfo: ProjectInfo,
): string {
  const { trigger, expectation } = hypothesis;

  return `// Auto-generated by Dendro Verified Projection
// Hypothesis: ${hypothesis.id} (hook state, confidence: ${hypothesis.confidence.toFixed(2)})
// ${hypothesis.reasoning}

import React from 'react';
import { render } from '${projectInfo.testingLibrary}';
import ${trigger.component} from '${trigger.file}';

describe('Hook State: ${trigger.component}.${expectation.property}', () => {
  it('should render without crashing (state "${expectation.property}" is used)', () => {
    // Render the component — verifies useState initialization works
    const { unmount } = render(<${trigger.component} />);

    // Component rendered successfully with state "${expectation.property}"
    // This confirms the hook state is properly initialized.
    // More specific assertions require knowledge of the component's render output
    // (e.g., testID attributes, text content), which will be available in v1.1.
    expect(true).toBe(true);

    unmount();
  });
});
`;
}

// --- Main Entry Point ---

/**
 * Generate test files from state flow hypotheses.
 *
 * Creates the __dendro__/ directory infrastructure and writes test files
 * for each hypothesis using the appropriate template.
 */
export function generateFlowTests(input: GenerateFlowTestInput): GenerateFlowTestResult {
  const { hypotheses, workspaceRoot } = input;

  if (!hypotheses || hypotheses.length === 0) {
    return {
      tests: [],
      jestConfigPath: '',
      warnings: ['No hypotheses provided.'],
    };
  }

  const absoluteRoot = assertPathInWorkspace(workspaceRoot, 'workspaceRoot');

  // Detect project setup
  const projectInfo = detectProjectInfo(absoluteRoot);
  const ext = projectInfo.isTypeScript ? 'tsx' : 'jsx';

  // Create __dendro__/ infrastructure
  const { testsDir, jestConfigPath, warnings } = ensureDendroDir(absoluteRoot, projectInfo);

  // Generate test files
  const tests: GeneratedTest[] = [];

  for (const hypothesis of hypotheses) {
    let testCode: string;

    switch (hypothesis.flowType) {
      case 'context':
        testCode = generateContextTest(hypothesis, projectInfo);
        break;
      case 'prop':
        testCode = generatePropTest(hypothesis, projectInfo);
        break;
      case 'hook-state':
        testCode = generateHookStateTest(hypothesis, projectInfo);
        break;
      default:
        warnings.push(`Unknown flow type "${hypothesis.flowType}" for hypothesis ${hypothesis.id}`);
        continue;
    }

    const testFileName = `flow-${hypothesis.id}.test.${ext}`;
    const testFilePath = path.join(testsDir, testFileName);

    // Write the test file
    fs.writeFileSync(testFilePath, testCode, 'utf-8');

    // Determine dependencies
    const dependencies = [projectInfo.testingLibrary];
    if (projectInfo.isTypeScript) {
      dependencies.push('@types/jest');
    }

    tests.push({
      hypothesisId: hypothesis.id,
      testCode,
      testFilePath,
      dependencies,
      flowType: hypothesis.flowType,
      isTypeScript: projectInfo.isTypeScript,
    });
  }

  return { tests, jestConfigPath, warnings };
}
